name: CI NPM pipeline

on:
  pull_request:
     branches:
       - "*"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setting up Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 15

      - name: Install Depedencies
        run: npm install

      - name: Run Linter
        run: npm run lint

      - name: Run formatter
        run: npm run prettier -- ––write

      - name: Run tests with Jest
        run: CI=true npm run test

      - name: Build the app
        run: npm run build




